import wx
meihuaA = wx.Image('90/mh1.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua2 = wx.Image('90/mh2.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua3 = wx.Image('90/mh3.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua4 = wx.Image('90/mh4.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua5 = wx.Image('90/mh5.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua6 = wx.Image('90/mh6.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua7 = wx.Image('90/mh7.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua8 = wx.Image('90/mh8.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua9 = wx.Image('90/mh9.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihua10 = wx.Image('90/mh10.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihuaJ = wx.Image('90/mhj.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihuaQ = wx.Image('90/mhq.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
meihuaK = wx.Image('90/mhk.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtaoA = wx.Image('90/ht1.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao2 = wx.Image('90/ht2.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao3 = wx.Image('90/ht3.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao4 = wx.Image('90/ht4.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao5 = wx.Image('90/ht5.jpg', wx.BITMAP_TYPE_JPEG).ConvertToBitmap()
hongtao6 = wx.Image('90/ht6.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao7 = wx.Image('90/ht7.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao8 = wx.Image('90/ht8.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao9 = wx.Image('90/ht9.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtao10 = wx.Image('90/ht10.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtaoJ = wx.Image('90/htj.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtaoQ = wx.Image('90/htq.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
hongtaoK = wx.Image('90/htk.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitaoA = wx.Image('90/htt1.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao2 = wx.Image('90/htt2.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao3 = wx.Image('90/htt3.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao4 = wx.Image('90/htt4.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao5 = wx.Image('90/htt5.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao6 = wx.Image('90/htt6.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao7 = wx.Image('90/htt7.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao8 = wx.Image('90/htt8.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao9 = wx.Image('90/htt9.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitao10 = wx.Image('90/htt10.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitaoJ = wx.Image('90/httj.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitaoQ = wx.Image('90/httq.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
heitaoK = wx.Image('90/httk.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpianA = wx.Image('90/fp1.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpian2 = wx.Image('90/fp2.jpg', wx.BITMAP_TYPE_JPEG).ConvertToBitmap()
fangpian3 = wx.Image('90/fp3.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpian4 = wx.Image('90/fp4.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpian5 = wx.Image('90/fp5.jpg', wx.BITMAP_TYPE_JPEG).ConvertToBitmap()
fangpian6 = wx.Image('90/fp6.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpian7 = wx.Image('90/fp7.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpian8 = wx.Image('90/fp8.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpian9 = wx.Image('90/fp9.jpg', wx.BITMAP_TYPE_JPEG).ConvertToBitmap()
fangpian10 = wx.Image('90/fp10.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpianJ = wx.Image('90/fpj.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpianQ = wx.Image('90/fpq.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
fangpianK = wx.Image('90/fpk.png', wx.BITMAP_TYPE_PNG).ConvertToBitmap()
tupianzidian={'meihuaA':meihuaA,'meihua2':meihua2,'meihua3':meihua3,'meihua4':meihua4,'meihua5':meihua5,'meihua6':meihua6,
                      'meihua7':meihua7,'meihua8':meihua8,'meihua9':meihua9,'meihua10':meihua10,'meihuaJ':meihuaJ,'meihuaQ':meihuaQ,'meihuaK':meihuaK,
                      'hongtaoA':hongtaoA,'hongtao2':hongtao2,'hongtao3':hongtao3,'hongtao4':hongtao4,'hongtao5':hongtao5,'hongtao6':hongtao6,
                      'hongtao7':hongtao7,'hongtao8':hongtao8,'hongtao9':hongtao9,'hongtao10':hongtao10,'hongtaoJ':hongtaoJ,'hongtaoQ':hongtaoQ,
                      'hongtaoK':hongtaoK,'heitaoA':heitaoA,'heitao2':heitao2,'heitao3':heitao3,'heitao4':heitao4,'heitao5':heitao5,'heitao6':heitao6,
                      'heitao7':heitao7,'heitao8':heitao8,'heitao9':heitao9,'heitao10':heitao10,'heitaoJ':heitaoJ,'heitaoQ':heitaoQ,'heitaoK':heitaoK,
                      'fangpianA':fangpianA,'fangpian2':fangpian2,'fangpian3':fangpian3,'fangpian4':fangpian4,'fangpian5':fangpian5,'fangpian6':fangpian6,
                      'fangpian7':fangpian7,'fangpian8':fangpian8,'fangpian9':fangpian9,'fangpian10':fangpian10,'fangpianJ':fangpianJ,'fangpianQ':fangpianQ,
                      'fangpianK':fangpianK}